name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install black isort

      - name: Get modified files
        uses: nrwl/last-successful-commit-action@v1
        with:
          branch: "main"
          workflow_id: "lint.yaml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
        id: modified_files
        run: |
          git diff --name-only ${{ steps.modified_files.outputs.commit_hash }} ${{ github.event.after }}
          files=$(git diff --name-only ${{ steps.modified_files.outputs.commit_hash }} ${{ github.event.after }} | grep ".py$" || echo "")
          echo "files<<EOF" >> $GITHUB_ENV
          echo "$files" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Format files
        run: |
          if [ -n "$files" ]; then
            echo "Formatting files:"
            for file in $files; do
              isort $file
              black $file
            done
          else
            echo "No Python files to format"
          fi

      - name: Commit and push changes
        if: steps.modified_files.outputs.files != ''
        run: |
          if [ -n "$files" ]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            for file in $files; do
              git add $file
            done
            git commit -m "Format"
            git push
          fi