name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install black isort

      - name: Get modified files
        id: modified_files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep ".py$")
          echo "files=$files" >> $GITHUB_OUTPUT

      - name: Format files
        run: |
          if [ -n "${{ steps.modified_files.outputs.files }}" ]; then
            echo "Formatting files:"
            isort ${{ steps.modified_files.outputs.files }}
            black ${{ steps.modified_files.outputs.files }}
          else
            echo "No Python files to format"
          fi

      - name: Commit and push changes
        if: steps.modified_files.outputs.files != ''
        run: |
          if [ -n "${{ steps.modified_files.outputs.files }}" ]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add ${{ steps.modified_files.outputs.files }}
            git commit -m "Format"
            git push
          fi