name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install black isort

      - name: Get modified files
        id: modified_files
        run: |
          # Get the list of modified Python files
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -E '\.py$')
          echo "Modified files: $files"
          echo "files=$files" >> $GITHUB_ENV

      - name: Run isort on modified files
        run: |
          if [ -n "$files" ]; then
            isort $files
          else
            echo "No Python files to sort"
          fi

      - name: Run Black on modified files
        run: |
          if [ -n "$files" ]; then
            black --check $files
          else
            echo "No Python files to format"
          fi

      - name: Commit and push changes
        if: success() && github.event_name == 'push' && steps.modified_files.outputs.files != ''
        run: |
          if [ -n "$files" ]; then
            isort $files
            black $files
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add $files
            git commit -m "Format" || echo "No changes to commit"
            git push
          else
            echo "No changes to commit"
          fi